version: '3.8'

services:
  mysql:
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    networks:
      - app

  postgres:
    image: postgres:13.1
    restart: always
    environment:
      POSTGRES_USER: ytbapi
      POSTGRES_PASSWORD: example
      POSTGRES_DB: ytb
    networks:
      - app
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - mysql
    networks:
      - app
  youtube:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - mysql
      - adminer
    volumes:
      - ./src:/usr/src/app/src
networks:
  app: